carousel({id:'carousel_3',
          border:'',
          size_mode:'image',
          width:150,
          height:100,
          sides:8,
          steps:8,
          speed:6,
          direction:'top',
          images:[	'immagini/imgmin/foto4.gif',
					'immagini/imgmin/foto2.gif',
					'immagini/imgmin/foto3.gif',
					'immagini/imgmin/foto1.gif'],
					
          links: [	'immagini/imgmax/foto4.jpg',
					'immagini/imgmax/foto2.jpg',
					'immagini/imgmax/foto3.jpg',
					'immagini/imgmax/foto1.jpg'],
          lnk_base:'rel="lightbox"',
          lnk_targets:['photo', //link target for each link (see: http://www.codingforums.com/showthread.php?t=58814&page=2)
                       'photo',
                       '_blank',
                       '_top.steve'],
          lnk_attr:['rel="lightbox"'],
          titles:['a',
                  'b',
                  'c',
                  'd'],
          image_border_width:1,
          image_border_color:'black'
          });